# Welcome to Jekyll!
#

# Site settings
title: Abhijeet Pasalkar
description: Traveller
owner: Abhijeet Pasalkar # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: mail@abhijeetpasalkar.in
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abhijeetpasalkar.in" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Abpasalkar
  github: https://github.com/adpasalkar
  linkedin-square: https://www.linkedin.com/in/abhijeet-p-01614134/
  facebook-official: https://www.facebook.com/abhijeet.pasalkar
  google-plus-square: https://plus.google.com/u/0/+adpasalkar
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/adpasalkar
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
